#!/bin/bash

if [ -z "$1" ]; then
  echo "Usage: $0 <dir>"
  exit 1
fi

if [ ! -d "$1" ]; then
  echo "Error: directory does not exist"
  exit 2
fi

DIR="$1"
DATE=$(date +"%Y-%m-%d")
ARCHIVE="${DIR}-${DATE}.tar.gz"

tar czvf "$ARCHIVE" "$DIR"
