#!/bin/bash

WIDTH=20
HEIGHT=10

snake_x=(10 9 8)
snake_y=(5 5 5)

dir="RIGHT"

is_snake() {
  for i in "${!snake_x[@]}"; do
    if [[ ${snake_x[$i]} -eq $1 && ${snake_y[$i]} -eq $2 ]]; then
      return 0
    fi
  done
  return 1
}

move_snake() {
  for ((i=${#snake_x[@]}-1; i>0; i--)); do
    snake_x[$i]=${snake_x[$((i-1))]}
    snake_y[$i]=${snake_y[$((i-1))]}
  done

  case "$dir" in
    UP)    ((snake_y[0]--)) ;;
    DOWN)  ((snake_y[0]++)) ;;
    LEFT)  ((snake_x[0]--)) ;;
    RIGHT) ((snake_x[0]++)) ;;
  esac
}

while true; do
  read -rsn1 -t 0.1 key
  case "$key" in
    w) dir="UP" ;;
    s) dir="DOWN" ;;
    a) dir="LEFT" ;;
    d) dir="RIGHT" ;;
  esac

  move_snake
  clear

  for ((y=1; y<=HEIGHT; y++)); do
    for ((x=1; x<=WIDTH; x++)); do

      if [[ $y -eq 1 || $y -eq $HEIGHT || $x -eq 1 || $x -eq $WIDTH ]]; then
        printf "#"
      elif is_snake "$x" "$y"; then
        printf "O"
      else
        printf " "
      fi

    done
    printf "\n"
  done

  sleep 0.2
done

