#!/bin/bash

WIDTH=30
HEIGHT=15

snake_x=(15 14 13)
snake_y=(8 8 8)

dir="RIGHT"

food_x=10
food_y=5

is_snake() {
  for i in "${!snake_x[@]}"; do
    if [[ ${snake_x[$i]} -eq $1 && ${snake_y[$i]} -eq $2 ]]; then
      return 0
    fi
  done
  return 1
}

spawn_food() {
  while true; do
    food_x=$((RANDOM % (WIDTH-2) + 2))
    food_y=$((RANDOM % (HEIGHT-2) + 2))
    is_snake "$food_x" "$food_y" || break
  done
}

move_snake() {
  local grow=0

  if [[ ${snake_x[0]} -eq $food_x && ${snake_y[0]} -eq $food_y ]]; then
    grow=1
    spawn_food
  fi

  if [[ $grow -eq 0 ]]; then
    unset 'snake_x[-1]'
    unset 'snake_y[-1]'
  fi

  case "$dir" in
    UP)    snake_x=(${snake_x[0]} "${snake_x[@]}"); snake_y=($((snake_y[0]-1)) "${snake_y[@]}") ;;
    DOWN)  snake_x=(${snake_x[0]} "${snake_x[@]}"); snake_y=($((snake_y[0]+1)) "${snake_y[@]}") ;;
    LEFT)  snake_x=($((snake_x[0]-1)) "${snake_x[@]}"); snake_y=(${snake_y[0]} "${snake_y[@]}") ;;
    RIGHT) snake_x=($((snake_x[0]+1)) "${snake_x[@]}"); snake_y=(${snake_y[0]} "${snake_y[@]}") ;;
  esac

  local head_x=${snake_x[0]}
  local head_y=${snake_y[0]}

  if [[ $head_x -le 1 || $head_x -ge $WIDTH || $head_y -le 1 || $head_y -ge $HEIGHT ]]; then
    echo "GAME OVER! Hit the wall."
    exit
  fi

  for ((i=1; i<${#snake_x[@]}; i++)); do
    if [[ ${snake_x[$i]} -eq $head_x && ${snake_y[$i]} -eq $head_y ]]; then
      echo "GAME OVER! Ran into yourself."
      exit
    fi
  done
}

spawn_food

while true; do
  read -rsn1 -t 0.1 key
  case "$key" in
    w) [[ $dir != "DOWN"  ]] && dir="UP" ;;
    s) [[ $dir != "UP"    ]] && dir="DOWN" ;;
    a) [[ $dir != "RIGHT" ]] && dir="LEFT" ;;
    d) [[ $dir != "LEFT"  ]] && dir="RIGHT" ;;
  esac

  move_snake
  clear

  for ((y=1; y<=HEIGHT; y++)); do
    for ((x=1; x<=WIDTH; x++)); do
      if [[ $y -eq 1 || $y -eq $HEIGHT || $x -eq 1 || $x -eq $WIDTH ]]; then
        printf "#"
      elif [[ $x -eq $food_x && $y -eq $food_y ]]; then
        printf "@"
      elif is_snake "$x" "$y"; then
        printf "O"
      else
        printf " "
      fi
    done
    printf "\n"
  done

  sleep 0.15
done



